spring:
  application:
    name: regula-ai-backend
  datasource:
    url: 'jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require'
    username: '${DB_USER}'
    password: '${DB_PASSWORD}'
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    open-in-view: false
  config:
    import: optional:file:.env[.properties]
  flyway:
    enabled: true
    baseline-on-migrate: true